spring:
  rabbitmq:
    username: ${AMQP_USER}
    password: ${AMQP_PASSWORD}
    host: ${AMQP_HOST}
    virtual-host: ${AMQP_VIRTUAL_HOST}
estating:
  api:
    url: ${ESTATING_API_URL:https://api-test.estating.com}
    username: ${ESTATING_API_USERNAME}
    password: ${ESTATING_API_PASSWORD}
